library(dplyr); library(stringr)

unidades <- readxl::read_excel("data-raw/classificacao_unidades_SEJUSP.xlsx")

unidades <- normalize_text_descunid(unidades) %>% as.data.table()


unidades_prisionais_regex <- "^CADEIA PUBLICA|^CERESP|^COMPLEXO PENITENCIARIO|^PENITENCIARIA|^PRESIDIO|^CARCERAGEM|^CASA DA ALBERGADA|^CASA DO ALBERGADO|^CENTRO DE APOIO MEDICO E PERICIAL|^COMANDO DE OPERACOES ESPECIAIS|^CENTRO DE REMANEJAMENTO DO SISTEMA PRISIONAL|^CENTRAL INTEGRADA DE ESC?OLTA DO SISTEMA PRISIONAL|^CENTRO DE REFERENCIA DA GESTANTE PRIVADA DE ?LIBERDADE|^HOSPITAL DE TOXICOMANOS PADRE WILSON VALE DA COSTA$|^HOSPITAL PSIQUIATRICO E JUDICIARIO JORGE VAZ$"
unidades_policiais_regex <- "^CASA DE CUSTODIA DA POLICIA CIVIL|^DELEGACIA|^CENTRAL DE RECEPCAO DE FLAGRANTES DO SISTEMA DEDEFESA SOCIAL E DA JUSTICA CRIMINAL"

unidades_socioeducativas_regex <- "^CASA DE SEMI ?LIBERD?ADE|^CENTRO SOCIOEDUCATIVO|^CENTRO DE INTERNACAO PROVISORIA|^DELEGACIA DE ORIENTACAO E PROTECAO A CRIANCA E AO ?ADOLESCENTE|^CENTRO DE INTERNACAO DO ADOLESCENTE|^CENTRO DE ATENDIMENTO AO ADOLESCENTE$|^CENTRO DE ENCAMINHAMENTO DA SEMILIBERDADE$|^CENTRO DE INTEGRACAO DA MENOR INFRATORA$|^CENTRO DE INTERNACAO SANCAO$|^CENTRO DE REEDUCACAO SOCIAL SAO JERONIMO$|^CENTRO INTEGRADO DE ATENDIMENTO AO ADOLESCENTE ?AUTOR DE ATO INFRACIONAL$"
unidades_prevencao_criminalidade_regex <- "^CENTRO DE PREVENCAO SOCIAL A CRIMINALIDADE TAQUARIL"

unidades[
  grepl(unidades_prisionais_regex, descunid), SIGILO := "INF. SIGILOSA TCI 4.06.145"
]

unidades[
  grepl(unidades_policiais_regex, descunid), SIGILO := "INF. SIGILOSA TCI 4.06.145"
]

unidades[
  grepl(unidades_socioeducativas_regex, descunid), SIGILO := "INF. SIGILOSA TCI 22.06.1690"
]

unidades[
  grepl(unidades_prevencao_criminalidade_regex, descunid), SIGILO := "INF. SIGILOSA TCI 22.06.1690"
]

